'history_len': 5
'receding_horizon': 10
'decaying_gammas':
  - 0.2
  - 0.4
  - 0.6
  - 0.8
  - 1.0
'bs': 64
'epoch': 1000
'test_every': 25
'opt_name': 'Adam'
'opt_config': {
  'lr': 0.001 }
'seed_num': 0